-- MySQL Script generated by MySQL Workbench
-- Wed 24 Apr 2024 05:14:02 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs340_janzenm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cs340_janzenm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs340_janzenm` ;
USE `cs340_janzenm` ;

-- -----------------------------------------------------
-- Table `cs340_janzenm`.`Patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs340_janzenm`.`Patients` ;

CREATE TABLE IF NOT EXISTS `cs340_janzenm`.`Patients` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `DOB` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  PRIMARY KEY (`patient_id`),
  UNIQUE INDEX `PatientID_UNIQUE` (`patient_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_janzenm`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs340_janzenm`.`Departments` ;

CREATE TABLE IF NOT EXISTS `cs340_janzenm`.`Departments` (
  `department_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_janzenm`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs340_janzenm`.`Employees` ;

CREATE TABLE IF NOT EXISTS `cs340_janzenm`.`Employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `Departments_department_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_Employees_Departments1_idx` (`Departments_department_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Departments1`
    FOREIGN KEY (`Departments_department_id`)
    REFERENCES `cs340_janzenm`.`Departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_janzenm`.`Procedures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs340_janzenm`.`Procedures` ;

CREATE TABLE IF NOT EXISTS `cs340_janzenm`.`Procedures` (
  `procedure_name` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  `required_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`procedure_name`),
  UNIQUE INDEX `procedure_name_UNIQUE` (`procedure_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_janzenm`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs340_janzenm`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `cs340_janzenm`.`Schedule` (
  `slot_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `time_slot` INT NOT NULL,
  `Procedures_procedure_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`slot_id`),
  UNIQUE INDEX `slot_id_UNIQUE` (`slot_id` ASC) VISIBLE,
  INDEX `fk_Schedule_Procedures1_idx` (`Procedures_procedure_name` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Procedures1`
    FOREIGN KEY (`Procedures_procedure_name`)
    REFERENCES `cs340_janzenm`.`Procedures` (`procedure_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_janzenm`.`Employees_has_Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs340_janzenm`.`Employees_has_Schedule` ;

CREATE TABLE IF NOT EXISTS `cs340_janzenm`.`Employees_has_Schedule` (
  `Employees_employee_id` INT NOT NULL,
  `Schedule_slot_id` INT NOT NULL,
  PRIMARY KEY (`Employees_employee_id`, `Schedule_slot_id`),
  INDEX `fk_Employees_has_Schedule_Schedule1_idx` (`Schedule_slot_id` ASC) VISIBLE,
  INDEX `fk_Employees_has_Schedule_Employees1_idx` (`Employees_employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_has_Schedule_Employees1`
    FOREIGN KEY (`Employees_employee_id`)
    REFERENCES `cs340_janzenm`.`Employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_has_Schedule_Schedule1`
    FOREIGN KEY (`Schedule_slot_id`)
    REFERENCES `cs340_janzenm`.`Schedule` (`slot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_janzenm`.`Patients_has_Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs340_janzenm`.`Patients_has_Schedule` ;

CREATE TABLE IF NOT EXISTS `cs340_janzenm`.`Patients_has_Schedule` (
  `Patients_patient_id` INT NOT NULL,
  `Schedule_slot_id` INT NOT NULL,
  PRIMARY KEY (`Patients_patient_id`, `Schedule_slot_id`),
  INDEX `fk_Patients_has_Schedule_Schedule1_idx` (`Schedule_slot_id` ASC) VISIBLE,
  INDEX `fk_Patients_has_Schedule_Patients1_idx` (`Patients_patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Patients_has_Schedule_Patients1`
    FOREIGN KEY (`Patients_patient_id`)
    REFERENCES `cs340_janzenm`.`Patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patients_has_Schedule_Schedule1`
    FOREIGN KEY (`Schedule_slot_id`)
    REFERENCES `cs340_janzenm`.`Schedule` (`slot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
